const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{Player: 0},
	{Lane1: 0},
	{Lane3: 0},
	{Lane2: 0},
	{Touch: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{EnemyHP: 0},
	{MoveTo: 0},
	{Enemy: 0},
	{Pin: 0},
	{txt_EnemyHP: 0},
	{txt_Score: 0},
	{txt_Lives: 0},
	{BasedLine: 0},
	{btn_Retry: 0},
	{par_enemy: 0},
	{par_Player: 0},
	{Audio: 0},
	{score: 0},
	{lives: 0},
	{difficulty: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Lane1: class extends self.ITiledBackgroundInstance {},
	Lane3: class extends self.ITiledBackgroundInstance {},
	Lane2: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	txt_EnemyHP: class extends self.ITextInstance {},
	txt_Score: class extends self.ITextInstance {},
	txt_Lives: class extends self.ITextInstance {},
	BasedLine: class extends self.ITiledBackgroundInstance {},
	btn_Retry: class extends self.ISpriteInstance {},
	par_enemy: class extends self.IParticlesInstance {},
	par_Player: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {}
}